project_id = "ieemfrbifclloaqfbdox"

[functions.send-department-notification]
verify_jwt = false

[functions.sql-server-sync]
verify_jwt = false

[functions.send-leave-notification]
verify_jwt = false
